CREATE TABLE nace17
(
	id_nace17 SERIAL PRIMARY KEY NOT NULL,
    code_section_nace17 CHARACTER VARYING,
    libelle_long CHARACTER VARYING,
    libelle CHARACTER VARYING,
    color CHARACTER VARYING
)
TABLESPACE pg_default;

