psql -d dashboard -c "\copy (select * from (select code_application as volet, count(*) as nombre_aides, sum(montant) as somme_montant, count(distinct siret) as nombre_siret_unique from aide where SUBSTR(categoriejuridiqueunitelegale,1,2) = '92' group by code_application) tbl where nombre_siret_unique > 2) TO '/tmp/1_general.csv' DELIMITER ',' CSV HEADER;"
mv /tmp/1_general.csv ../data/ccompte-extract/

psql -d dashboard -c "\copy (select * from (select code_application as volet, SUBSTR(CAST(date_paiement as text),1,7) as mois, count(*) as nombre_aides, sum(montant) as somme_montant, count(distinct siret) as nombre_siret_unique from aide where SUBSTR(categoriejuridiqueunitelegale,1,2) = '92' group by SUBSTR(CAST(date_paiement as text),1,7), code_application) tbl where nombre_siret_unique > 2) TO '/tmp/2_mensuel.csv' DELIMITER ',' CSV HEADER;"
mv /tmp/2_mensuel.csv ../data/ccompte-extract/

psql -d dashboard -c "\copy (select * from (select SUBSTR(CAST(A.date_paiement as text),1,7) as mois, A.reg as code_region, R.libelle as region, count(*) as nombre_aides, sum(A.montant) as somme_montant, count(distinct A.siret) as nombre_siret_unique from aide A LEFT JOIN region R ON R.reg = A.reg where SUBSTR(categoriejuridiqueunitelegale,1,2) = '92' and A.reg is not null group by SUBSTR(CAST(A.date_paiement as text),1,7), A.reg, R.libelle) tbl where nombre_siret_unique > 2 order by mois, code_region) TO '/tmp/3_mensuel_region.csv' DELIMITER ',' CSV HEADER;"
mv /tmp/3_mensuel_region.csv ../data/ccompte-extract/

psql -d dashboard -c "\copy (select * from (select SUBSTR(CAST(A.date_paiement as text),1,7) as mois, A.reg as code_region, R.libelle as region, A.dep as code_departement, D.libelle as departement, count(*) as nombre_aides, sum(A.montant) as somme_montant, count(distinct A.siret) as nombre_siret_unique from aide A LEFT JOIN region R ON R.reg = A.reg LEFT JOIN departement D ON A.dep = D.dep where SUBSTR(categoriejuridiqueunitelegale,1,2) = '92' and A.reg is not null group by SUBSTR(CAST(A.date_paiement as text),1,7), A.reg, R.libelle, A.dep, D.libelle) tbl where nombre_siret_unique > 2 order by mois, code_region, code_departement) TO '/tmp/4_mensuel_departement.csv' DELIMITER ',' CSV HEADER;"
mv /tmp/4_mensuel_departement.csv ../data/ccompte-extract/

psql -d dashboard -c "\copy (select * from (select A.code_application as volet, REPLACE(A.activiteprincipaleetablissement, '.', '') as sous_classe_naf, N.libelle_sous_classe, count(*) as nombre_aides, sum(A.montant) as somme_montant, count(distinct A.siret) as nombre_siret_unique from aide A LEFT JOIN naf N ON REPLACE(A.activiteprincipaleetablissement, '.', '') = N.code_sous_classe_short where SUBSTR(categoriejuridiqueunitelegale,1,2) = '92' group by volet, sous_classe_naf, libelle_sous_classe) tbl where nombre_siret_unique > 2 order by nombre_siret_unique desc) TO '/tmp/5_ape.csv' DELIMITER ',' CSV HEADER;"
mv /tmp/5_ape.csv ../data/ccompte-extract/

psql -d dashboard -c "\copy (select * from (select A.code_application as volet, SUBSTR(CAST(A.date_paiement as text),1,7) as mois, REPLACE(A.activiteprincipaleetablissement, '.', '') as sous_classe_naf, N.libelle_sous_classe, count(*) as nombre_aides, sum(A.montant) as somme_montant, count(distinct A.siret) as nombre_siret_unique from aide A LEFT JOIN naf N ON REPLACE(A.activiteprincipaleetablissement, '.', '') = N.code_sous_classe_short where SUBSTR(categoriejuridiqueunitelegale,1,2) = '92' group by volet, SUBSTR(CAST(A.date_paiement as text),1,7), sous_classe_naf, libelle_sous_classe) tbl where nombre_siret_unique > 2 order by mois, nombre_siret_unique desc) TO '/tmp/6_ape_mensuel.csv' DELIMITER ',' CSV HEADER;"
mv /tmp/6_ape_mensuel.csv ../data/ccompte-extract/

psql -d dashboard -c "\copy (select * from (select A.code_application as volet, SUBSTR(CAST(A.date_paiement as text),1,7) as mois, A.reg as code_region, R.libelle as region, REPLACE(A.activiteprincipaleetablissement, '.', '') as sous_classe_naf, N.libelle_sous_classe, count(*) as nombre_aides, sum(A.montant) as somme_montant, count(distinct A.siret) as nombre_siret_unique from aide A LEFT JOIN naf N ON REPLACE(A.activiteprincipaleetablissement, '.', '') = N.code_sous_classe_short LEFT JOIN region R ON R.reg = A.reg where SUBSTR(categoriejuridiqueunitelegale,1,2) = '92' group by volet, SUBSTR(CAST(A.date_paiement as text),1,7), A.reg, R.libelle, sous_classe_naf, libelle_sous_classe) tbl where nombre_siret_unique > 2 order by mois, code_region, nombre_siret_unique desc) TO '/tmp/7_ape_mensuel_region.csv' DELIMITER ',' CSV HEADER;"
mv /tmp/7_ape_mensuel_region.csv ../data/ccompte-extract/

psql -d dashboard -c "\copy (select * from (select A.code_application as volet, SUBSTR(CAST(A.date_paiement as text),1,7) as mois, A.reg as code_region, R.libelle as region, A.dep as code_departement, D.libelle as departement, REPLACE(A.activiteprincipaleetablissement, '.', '') as sous_classe_naf, N.libelle_sous_classe, count(*) as nombre_aides, sum(A.montant) as somme_montant, count(distinct A.siret) as nombre_siret_unique from aide A LEFT JOIN naf N ON REPLACE(A.activiteprincipaleetablissement, '.', '') = N.code_sous_classe_short LEFT JOIN region R ON R.reg = A.reg LEFT JOIN departement D ON D.dep = A.dep where SUBSTR(categoriejuridiqueunitelegale,1,2) = '92' group by volet, SUBSTR(CAST(A.date_paiement as text),1,7), A.reg, R.libelle, A.dep, D.libelle, sous_classe_naf, libelle_sous_classe) tbl where nombre_siret_unique > 2 order by mois, code_region, code_departement, nombre_siret_unique desc) TO '/tmp/8_ape_mensuel_departement.csv' DELIMITER ',' CSV HEADER;"
mv /tmp/8_ape_mensuel_departement.csv ../data/ccompte-extract/

python 99_generate_xlsx_ccompte_association.py

